### ISSUE TITLE
Error tras recuperar objeto del LocalStorage

### ISSUE THREAD

**Issue by ReynerHL** [lusaxweb/vuenut#1]
You have in the official website [https://lusaxweb.github.io/vuenut.org/] this issue.

The method **consultarFunctions** from the component **myFunctions.vue**, is not taking care about the posibility that the item recovered from the localStorage could be empty.

Translated to Spanish:
------------------------
En el sitio oficial [https://lusaxweb.github.io/vuenut.org/] tiene el caso de reproducción.

Al parecer en el componente **myFunctions.vue** en el método **consultarFunctions**, no se está controlando la posibilidad de que el valor recuperado del localStorage sea vacío.

**Comment by luisDanielRoviraContreras** [comment]
Ready friend already solve it, thank you very much if you want to check to see if the problem repeats

https://lusaxweb.github.io/vuenut.org/

**Comment by ReynerHL** [comment]
Well done !! Thanks !!.

This is a really nice project. I know it is in its very early stage, but you shouldn't neglect the difference between development code and the final code you publish. What I'm trying to target here is the lot of anoying console.log/dir you have that flood our console with funny message like "hola", "paso por aquí...", etc.

Thanks again for your effort doing this tool for the vue community.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for the calm contribution I will improve in that aspect thanks
