### ISSUE TITLE
Uncaught error in JSonView when an state entry has null as value.

### ISSUE THREAD

**Issue by ReynerHL** [lusaxweb/vuenut#2]
If an entry in our state has null as value, we reach this error:
**TypeError: Cannot convert undefined or null to object**

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much I will review the error to solve it as soon as I have it ready you notice

**Comment by luisDanielRoviraContreras** [comment]
ready friend already solve the problem thank you very much for the contribution

[Relase](https://github.com/lusaxweb/vuenut/releases/tag/v0.1.32)

**Comment by ReynerHL** [comment]
Exception controlled. Well done !! But null values should be allowed to be edited as well. This will fix the strange behaviour when we clean a node in the store state and the JsonView node lose the focus, when we go back to the JsonView node, this node is not editable anymore.

SPANISH TRANSLATION:

La excepción fue controlada. Bien hecho. Pero también se debería permitir editar los valores que quedan en null en el JsonView. Esto solucionaría el comportamiento raro el que por ejemplo, limpiamos por completo un valor de un nodo, y damos click en otro nodo, al perder el foco también perdemos la posibilidad de volver a editar el nodo que limpiamos por completo. Al parecer, no se puede editar un nodo que tiene por valor null. Dime si prefieres que abra un nuevo issue, o si ya voy por el tercer strike 😄 .
