### ISSUE TITLE
Night Mode Icon color styling

### ISSUE THREAD

**Issue by akinhwan** [lusaxweb/vuenut#3]
First off, an amazing tool! This really is a very minor issue.
I want to assign this to myself, but just posting as an issue to see if people agree?
I could make these changes in the css, as I've done in dev tools just experimentally.

Currently the icons are difficult to see in 'night mode'.

![dev tools changed icon colors](https://user-images.githubusercontent.com/10124722/39217009-0da17ad6-47ec-11e8-9783-279defe9bcbb.png)
Above is my proposed change with new icon color as white for higher contrast, and better accessibility.

**Comment by luisDanielRoviraContreras** [comment]
Excellent friend very good contribution you have the whole reason I'm going to change it and I'll thank you very much
