### ISSUE TITLE
Unable to edit a JSonView entry after its value goes null

### ISSUE THREAD

**Issue by ReynerHL** [lusaxweb/vuenut#4]
If we remove the entire value of an entry from the jsonview, and it misses the focus (clicking another entry in the jsonview), we are not able to set a value in that entry anymore.

Null value should be treated as another value after all.

**Comment by luisDanielRoviraContreras** [comment]
@ReynerHL Ready friend is already ready thank you very much for the contribution

- [Release](https://github.com/lusaxweb/vuenut/releases/tag/v0.2.1)

**Comment by ReynerHL** [comment]
@luisDanielRoviraContreras Thanks you so much for your effort. It already allow us to edit null values now, but the problem persist when you left a node with an empty string. In fact, we can edit it if we change to the "raw" JSONViewer, but not with the "html input tag", it is like if once that nodes goes with an empty string, the input tag could not render itself anymore. I feel you are very close to fix this.

Thanks again for your contribution.

**Comment by luisDanielRoviraContreras** [comment]
You could give me an example in images of the problem to attack it exactly thank you very much

**Comment by ReynerHL** [comment]
Hi @luisDanielRoviraContreras . Sure, take a look at this screenshot. It was taken from https://lusaxweb.github.io/vuenut.org/ , the problem is with the input element in the JSONView component. After it gets an empty string (take its value and delete its content using backspace or delete), if you click out and try later to use that node again, the input tag did not render anymore.

![image](https://user-images.githubusercontent.com/9044040/39970734-f965ddfc-56ad-11e8-9808-95bf2e1500e4.png)

**Comment by luisDanielRoviraContreras** [comment]
@ReynerHL Okay, I'm going to review it and fix it, thank you very much for the contribution
